diff --git a/images/capi/.dockerignore b/images/capi/.dockerignore
index e474674ca..565293fe8 100644
--- a/images/capi/.dockerignore
+++ b/images/capi/.dockerignore
@@ -9,3 +9,4 @@
 !packer
 !Makefile
 !azure_targets.sh
+!template.json
diff --git a/images/capi/Dockerfile b/images/capi/Dockerfile
index e9ace3ed6..c0bb40356 100644
--- a/images/capi/Dockerfile
+++ b/images/capi/Dockerfile
@@ -55,6 +55,7 @@ COPY --chown=imagebuilder:imagebuilder hack hack/
 COPY --chown=imagebuilder:imagebuilder packer packer/
 COPY --chown=imagebuilder:imagebuilder Makefile Makefile
 COPY --chown=imagebuilder:imagebuilder azure_targets.sh azure_targets.sh
+COPY --chown=imagebuilder:imagebuilder template.json template.json
 
 ENV PATH="/home/imagebuilder/.local/bin:${PATH}"
 ENV PACKER_ARGS=''
