
- name: Add 'kubelet' user
  ansible.builtin.user:
    name: kubelet

- name: Set users
  set_fact:
    subid_users:
      - kubelet

- name: Generate subuids & subgids
  include_role:
    name: subuid_subgid
  vars:
    subuid_uids: 7208960
    subgid_gids: 7208960
