
- name: Add 'kubelet' user
  ansible.builtin.user:
    name: kubelet

- name: Set subuids and subgid users
  set_fact:
    subid_users:
      - kubelet

- name: Generate subuids and subgid
  include_role:
    name: subuid_subgid
