
- name: Add 'kubelet' user
  ansible.builtin.user:
    name: kubelet

- name: Generate subuids and subgid
  include_role:
    name: subxid
  vars:
    subxid_size: 7208960
    uid: kubelet
    files: both
    found_strategy: fail
    subuid_file: /etc/subuid
    subgid_file: /etc/subgid
