- name: Install pre-requisites
  apt:
    name: "{{ item }}"
  loop: "{{ byoh_required_packages }}"

- name: Download byoh hostagent 
  get_url:
    url: https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/releases/download/{{ byoh_agent_version }}/byoh-hostagent-linux-amd64
    dest: /usr/bin/byoh-hostagent
    mode: 0755
    owner: root
    group: root

- name: Make byoh config folder exists
  file:
    path: "{{ byoh_configuration_path }}"
    state: directory
    owner: root
    group: root

# TODO Add the control plane flag for control planes and not for workers
- name: Add systemd unit 
  template:
    src: byoh-hostagent.service.j2
    dest: /etc/systemd/system/byoh-hostagent.service
    mode: 0644
    owner: root
    group: root

- name: Enable byoh hostagent systemd unit
  systemd:
    name: byoh-hostagent
    state: stopped # This will restart on next boot
    enabled: true
    daemon_reload: true
