name: Store OpenStack CAPI image on safespring

on:
  workflow_call:
    inputs:
      version:
        description: Kubernetes version
        required: true
        type: string
      tag:
        description: ck8s-capi tag
        required: true
        type: string

env:
  version: ${{ inputs.version }}
  tag: ${{ inputs.tag }}
  

jobs:
  on-success:
    runs-on: ubuntu-24.04

    steps:
      - name: retrieve image
        uses: actions/download-artifact@v5
        with:
          name: ubuntu-2404-efi-kube-${{ env.version }}-ck8s-capi-${{ env.tag }}

      - name: install deps
        run: |
          pip3 install python-openstackclient

      - name: store image
        env:
          OS_APPLICATION_CREDENTIAL_ID: ${{ secrets.SAFESPRING_APPLICATION_CREDENTIAL_ID }}
          OS_APPLICATION_CREDENTIAL_SECRET: ${{ secrets.SAFESPRING_APPLICATION_CREDENTIAL_SECRET }}
          OS_AUTH_URL: "https://v2.dashboard.sto1.safedc.net:5000/v3/"
          OS_AUTH_TYPE: "v3applicationcredential"
          OS_IDENTITY_API_VERSION: "3"
          OS_INTERFACE: "public"
          OS_REGION_NAME: "sto1"
        run: |

          image_create_extra_vars+=('--property' 'hw_firmware_type=uefi' '--property' 'hw_disk_bus=scsi' '--property' 'hw_scsi_model=virtio-scsi')
          image_name=ubuntu-2404-efi-kube-${{ env.version }}-ck8s-capi-${{ env.tag }}
          image_path=./ubuntu-2404-efi-kube-${{ env.version }}-ck8s-capi-${{ env.tag }}

          openstack image create --verbose --disk-format qcow2 "${image_create_extra_vars[@]}" --file "${image_path}" --shared --progress "${image_name}"

